"""Add UserPRPSAAssessment table for user-level anxiety assessments

Revision ID: 307ba8ea5639
Revises: e790fd466542
Create Date: 2025-11-09 15:45:33.817388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307ba8ea5639'
down_revision = 'e790fd466542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_prpsa_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assessment_type', sa.String(length=20), nullable=False),
    sa.Column('q1', sa.Integer(), nullable=False),
    sa.Column('q2', sa.Integer(), nullable=False),
    sa.Column('q3', sa.Integer(), nullable=False),
    sa.Column('q4', sa.Integer(), nullable=False),
    sa.Column('q5', sa.Integer(), nullable=False),
    sa.Column('q6', sa.Integer(), nullable=False),
    sa.Column('q7', sa.Integer(), nullable=False),
    sa.Column('q8', sa.Integer(), nullable=False),
    sa.Column('q9', sa.Integer(), nullable=False),
    sa.Column('q10', sa.Integer(), nullable=False),
    sa.Column('q11', sa.Integer(), nullable=False),
    sa.Column('q12', sa.Integer(), nullable=False),
    sa.Column('q13', sa.Integer(), nullable=False),
    sa.Column('q14', sa.Integer(), nullable=False),
    sa.Column('q15', sa.Integer(), nullable=False),
    sa.Column('q16', sa.Integer(), nullable=False),
    sa.Column('q17', sa.Integer(), nullable=False),
    sa.Column('q18', sa.Integer(), nullable=False),
    sa.Column('q19', sa.Integer(), nullable=False),
    sa.Column('q20', sa.Integer(), nullable=False),
    sa.Column('q21', sa.Integer(), nullable=False),
    sa.Column('q22', sa.Integer(), nullable=False),
    sa.Column('q23', sa.Integer(), nullable=False),
    sa.Column('q24', sa.Integer(), nullable=False),
    sa.Column('q25', sa.Integer(), nullable=False),
    sa.Column('q26', sa.Integer(), nullable=False),
    sa.Column('q27', sa.Integer(), nullable=False),
    sa.Column('q28', sa.Integer(), nullable=False),
    sa.Column('q29', sa.Integer(), nullable=False),
    sa.Column('q30', sa.Integer(), nullable=False),
    sa.Column('q31', sa.Integer(), nullable=False),
    sa.Column('q32', sa.Integer(), nullable=False),
    sa.Column('q33', sa.Integer(), nullable=False),
    sa.Column('q34', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('anxiety_level', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'assessment_type', name='_user_assessment_type_uc')
    )
    with op.batch_alter_table('user_prpsa_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_prpsa_assessments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_prpsa_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_prpsa_assessments_user_id'))

    op.drop_table('user_prpsa_assessments')
    # ### end Alembic commands ###
