"""Add new speech fields: goal, audience_description, key_points, self_improvement_goal

Revision ID: 816cd10e939b
Revises: 9b2148c1bd6e
Create Date: 2025-10-20 22:16:13.709302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816cd10e939b'
down_revision = '9b2148c1bd6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns as nullable first
    with op.batch_alter_table('speeches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audience_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('key_points', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('self_improvement_goal', sa.Text(), nullable=True))
    
    # Update existing records with default values
    speeches_table = sa.table('speeches',
        sa.column('audience_description', sa.Text),
        sa.column('goal', sa.Text)
    )
    
    # Set default values for existing records
    op.execute(
        speeches_table.update().values(
            audience_description='General audience (to be specified)'
        ).where(speeches_table.c.audience_description.is_(None))
    )
    
    # Set goal to description for existing records where goal is null
    op.execute(
        speeches_table.update().values(
            goal=sa.text("COALESCE(goal, description, 'To be specified')")
        ).where(speeches_table.c.goal.is_(None))
    )
    
    # Now make the required columns NOT NULL
    with op.batch_alter_table('speeches', schema=None) as batch_op:
        batch_op.alter_column('audience_description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('goal',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('speeches', schema=None) as batch_op:
        batch_op.alter_column('goal',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('self_improvement_goal')
        batch_op.drop_column('key_points')
        batch_op.drop_column('audience_description')

    # ### end Alembic commands ###
