"""Add user profile fields

Revision ID: 8a1047b0ac5d
Revises: 
Create Date: 2025-10-19 20:48:57.054509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a1047b0ac5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('picture', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('nickname', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('given_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('family_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('family_name')
        batch_op.drop_column('given_name')
        batch_op.drop_column('nickname')
        batch_op.drop_column('picture')
        batch_op.drop_column('name')
        batch_op.drop_column('email')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
