"""Refactor session model - remove self assessment and video analysis, add CSSEF scoring

Revision ID: 9f38a95fea6c
Revises: 67078bd7b589
Create Date: 2025-11-02 17:38:20.874088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f38a95fea6c'
down_revision = '67078bd7b589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prpsa_assessments', schema=None) as batch_op:
        batch_op.drop_constraint('prpsa_assessments_speech_id_key', type_='unique')
        batch_op.drop_index('ix_prpsa_assessments_speech_id')
        batch_op.create_index(batch_op.f('ix_prpsa_assessments_speech_id'), ['speech_id'], unique=True)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_summary', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('c1_topic_choice_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('c1_topic_choice_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('c1_topic_choice_improvement', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('c2_purpose_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('c2_purpose_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('c2_purpose_improvement', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('c3_supporting_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('c3_supporting_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('c3_supporting_improvement', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('c4_organization_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('c4_organization_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('c4_organization_improvement', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('c5_language_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('c5_language_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('c5_language_improvement', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('c6_vocal_variety_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('c6_vocal_variety_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('c6_vocal_variety_improvement', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('c7_pronunciation_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('c7_pronunciation_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('c7_pronunciation_improvement', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('revised_speech_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('revised_speech_audio_url', sa.String(length=2000), nullable=True))
        batch_op.drop_column('clarity_score')
        batch_op.drop_column('structure_score')
        batch_op.drop_column('video_analysis')
        batch_op.drop_column('confidence_score')
        batch_op.drop_column('gesture_rate')
        batch_op.drop_column('eye_contact_percentage')
        batch_op.drop_column('pronunciation_score')
        batch_op.drop_column('grammar_error_count')
        batch_op.drop_column('structure_quality')
        batch_op.drop_column('facial_expressiveness')
        batch_op.drop_column('engagement_score')
        batch_op.drop_column('readability_score')
        batch_op.drop_column('fluency_score')

    with op.batch_alter_table('speeches', schema=None) as batch_op:
        batch_op.alter_column('goal',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('audience_description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('context',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('with_context',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('speeches', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('with_context',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('context',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('audience_description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('goal',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fluency_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('readability_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('engagement_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('facial_expressiveness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('structure_quality', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('grammar_error_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pronunciation_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('eye_contact_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gesture_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('video_analysis', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('structure_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('clarity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('revised_speech_audio_url')
        batch_op.drop_column('revised_speech_text')
        batch_op.drop_column('c7_pronunciation_improvement')
        batch_op.drop_column('c7_pronunciation_comment')
        batch_op.drop_column('c7_pronunciation_score')
        batch_op.drop_column('c6_vocal_variety_improvement')
        batch_op.drop_column('c6_vocal_variety_comment')
        batch_op.drop_column('c6_vocal_variety_score')
        batch_op.drop_column('c5_language_improvement')
        batch_op.drop_column('c5_language_comment')
        batch_op.drop_column('c5_language_score')
        batch_op.drop_column('c4_organization_improvement')
        batch_op.drop_column('c4_organization_comment')
        batch_op.drop_column('c4_organization_score')
        batch_op.drop_column('c3_supporting_improvement')
        batch_op.drop_column('c3_supporting_comment')
        batch_op.drop_column('c3_supporting_score')
        batch_op.drop_column('c2_purpose_improvement')
        batch_op.drop_column('c2_purpose_comment')
        batch_op.drop_column('c2_purpose_score')
        batch_op.drop_column('c1_topic_choice_improvement')
        batch_op.drop_column('c1_topic_choice_comment')
        batch_op.drop_column('c1_topic_choice_score')
        batch_op.drop_column('feedback_summary')

    with op.batch_alter_table('prpsa_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prpsa_assessments_speech_id'))
        batch_op.create_index('ix_prpsa_assessments_speech_id', ['speech_id'], unique=False)
        batch_op.create_unique_constraint('prpsa_assessments_speech_id_key', ['speech_id'])

    # ### end Alembic commands ###
