"""increase media_url length for GCS signed URLs

Revision ID: a1b2c3d4e5f6
Revises: 816cd10e939b
Create Date: 2025-10-27 21:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '816cd10e939b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Increase media_url length from 500 to 2000 characters for GCS signed URLs
    op.alter_column('sessions', 'media_url',
                    existing_type=sa.VARCHAR(length=500),
                    type_=sa.String(length=2000),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert media_url length back to 500 characters
    op.alter_column('sessions', 'media_url',
                    existing_type=sa.String(length=2000),
                    type_=sa.VARCHAR(length=500),
                    existing_nullable=True)
    # ### end Alembic commands ###