"""add user self rating table

Revision ID: c1d2e3f4g5h6
Revises: a1b2c3d4e5f6
Create Date: 2025-10-27 21:45:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1d2e3f4g5h6'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_self_ratings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=False),
        sa.Column('c1_topic_choice_score', sa.Integer(), nullable=True),
        sa.Column('c1_topic_choice_comment', sa.Text(), nullable=True),
        sa.Column('c2_purpose_score', sa.Integer(), nullable=True),
        sa.Column('c2_purpose_comment', sa.Text(), nullable=True),
        sa.Column('c3_supporting_score', sa.Integer(), nullable=True),
        sa.Column('c3_supporting_comment', sa.Text(), nullable=True),
        sa.Column('c4_organization_score', sa.Integer(), nullable=True),
        sa.Column('c4_organization_comment', sa.Text(), nullable=True),
        sa.Column('c5_language_score', sa.Integer(), nullable=True),
        sa.Column('c5_language_comment', sa.Text(), nullable=True),
        sa.Column('c6_vocal_variety_score', sa.Integer(), nullable=True),
        sa.Column('c6_vocal_variety_comment', sa.Text(), nullable=True),
        sa.Column('c7_pronunciation_score', sa.Integer(), nullable=True),
        sa.Column('c7_pronunciation_comment', sa.Text(), nullable=True),
        sa.Column('c8_physical_score', sa.Integer(), nullable=True),
        sa.Column('c8_physical_comment', sa.Text(), nullable=True),
        sa.Column('overall_comment', sa.Text(), nullable=True),
        sa.Column('confidence_level', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_self_ratings_session_id'), 'user_self_ratings', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_self_ratings_session_id'), table_name='user_self_ratings')
    op.drop_table('user_self_ratings')
    # ### end Alembic commands ###